### ISSUE TITLE
Limited storage time

### ISSUE THREAD

**Issue by RonnyLam** [ahupowerdns/covid-backend#3]
Storage of infected id's is only relevant for a limited time, max 14 days. Although by design the id's alone are already privacy ensured, deleting them after 14 days (or 21 to be safe) ensures it even more. Of course they can be counted anonymously for reporting.

**Comment by spycrowsoft** [comment]
I think this question is addressed in the other issues as well, particularly in https://github.com/ahupowerdns/covid-backend/issues/7.

Please note that everything we distribute, automatically looses all it's informational value after the client-devices delete their own tracking history.

After all client devices delete their own history, what we distribute are "just large files of meaningless salted hashes". So even if we don't delete them or if they pop up somewhere else online later, the information in them is useless.

**Comment by RonnyLam** [comment]
This is indeed covered. Great work!
